import "@/app/styles.css";
import Menu from "./components/Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main">{children}</div>
        <Menu />
      </body>
    </html>
  );
}
